apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandaapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "pandaacademy/frontend:latest"
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: "http://pandaapp-backend: 5001/"